import type { AppConfig } from './types';

export function generateFiles(cfg: AppConfig): Record<string, string> {
  const name = `my-${cfg.frontend}-app`;
  const pkg: any = {
    name,
    private: true,
    version: '0.1.0',
    scripts: {
      dev: 'next dev',
      build: 'next build',
      start: 'next start'
    },
    dependencies: {}
  };

  if (cfg.frontend === 'next') {
    pkg.dependencies = {
      next: 'latest',
      react: 'latest',
      'react-dom': 'latest'
    };
  } else if (cfg.frontend === 'sveltekit') {
    pkg.scripts.dev = 'svelte-kit dev';
    pkg.dependencies = { '@sveltejs/kit': 'latest' };
  } else {
    pkg.dependencies = { react: 'latest' };
  }

  const readme = `# ${name}

Generated by Alsenda App Wizard.

Choices:
- Frontend: ${cfg.frontend}
- Data layer: ${cfg.dataLayer}
- Database: ${cfg.database}
- Auth: ${cfg.auth}
- Deploy: ${cfg.deploy}

To run:

1. npm install
2. npm run dev
`;

  const appPage = `import React from 'react';

export default function Page() {
  return (
    <main style={{padding:24,fontFamily:'monospace',background:'#000',color:'#fff',minHeight:'100vh'}}>
      <h1>${name}</h1>
      <p>Frontend: ${cfg.frontend}</p>
      <p>Data layer: ${cfg.dataLayer}</p>
      <p>Database: ${cfg.database}</p>
      <p>Auth: ${cfg.auth}</p>
      <p>Deploy target: ${cfg.deploy}</p>
    </main>
  );
}
`;

  const globals = `:root { color-scheme: dark; }
html,body,#root { height:100%; }
body { margin:0; font-family: Inter, system-ui, -apple-system, Segoe UI, Roboto, 'Helvetica Neue', Arial; background: #000; color:#fff }
`;

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}
module.exports = nextConfig
`;

  const files: Record<string, string> = {
    'README.md': readme,
    'package.json': JSON.stringify(pkg, null, 2),
    'app/page.tsx': appPage,
    'app/globals.css': globals,
    'app/layout.tsx': layoutTsx(),
    'app/head.tsx': headTsx(),
    'components/Header.tsx': headerComponent(),
    'tailwind.config.js': tailwindConfig(),
    'postcss.config.cjs': postcssConfig(),
    'next.config.js': nextConfig,
  };

  // Add minimal GitHub workflow if deploying to Vercel would be typical
  if (cfg.deploy === 'vercel') {
    files['.vercelignore'] = 'node_modules\n.next\n';
  }

  return files;
}

function layoutTsx(): string {
  return `import './globals.css'
import Header from '../components/Header'

export const metadata = {
  title: 'Alsenda App',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div style={{padding:24}}>{children}</div>
      </body>
    </html>
  )
}
`;
}

function headTsx(): string {
  return `export default function Head() {
  return (
    <>
      <meta name="viewport" content="width=device-width,initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
`;
}

function headerComponent(): string {
  return `import React from 'react'

export default function Header() {
  return (
    <header style={{padding:12,background:'#041',color:'#8ff'}}>
      <div style={{maxWidth:980,margin:'0 auto',display:'flex',alignItems:'center',gap:12}}>
        <div style={{fontFamily:'monospace',fontWeight:700}}>Alsenda App</div>
      </div>
    </header>
  )
}
`;
}

function tailwindConfig(): string {
  return `module.exports = {
  content: ['./app/**/*.{ts,tsx,js,jsx}', './components/**/*.{ts,tsx,js,jsx}'],
  theme: { extend: {} },
  plugins: [],
}
`;
}

function postcssConfig(): string {
  return `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
`;
}


export default generateFiles;
