import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CRTPageTransition from "@/components/CRTPageTransition";
import { ThemeProvider } from "@/components/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Feature flag: enable 3D headers when NEXT_PUBLIC_ENABLE_3D === 'true'
  const enableThreeD = process.env.NEXT_PUBLIC_ENABLE_3D === 'true';
  return (
    <html lang="en" data-three-d={enableThreeD}>
      <head>
        {/* Early theme application to avoid flash of default before hydration */}
        <script
          dangerouslySetInnerHTML={{
            __html: `!function(){try{var k='alsenda-theme';var v=localStorage.getItem(k);if(!v){var m=document.cookie.match(/(?:^|; )alsenda-theme=([^;]+)/);v=m&&m[1];}if(!v){v='ega';}document.documentElement.setAttribute('data-theme', v);}catch(e){}}();`
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `;(function(){
  try {
    const root = document.documentElement;

    function updateRootFromEvent(e){
      const t = e.touches && e.touches[0] ? e.touches[0] : e;
      const cx = t.clientX || (window.innerWidth/2);
      const cy = t.clientY || (window.innerHeight/2);
      const x = ((cx / window.innerWidth) - 0.5) * 2; // -1..1
      const y = ((cy / window.innerHeight) - 0.5) * -2; // invert y
      root.style.setProperty('--mx', x);
      root.style.setProperty('--my', y);
    }

    // per-element (local) mouse reaction for headers
    function attachHeaderListeners(){
      const els = document.querySelectorAll('h1,h2,h3,h4,h5,h6');
      els.forEach(el => {
        let rect = null;
        function onMove(e){
          const t = e.touches && e.touches[0] ? e.touches[0] : e;
          rect = rect || el.getBoundingClientRect();
          const cx = t.clientX;
          const cy = t.clientY;
          const x = ((cx - rect.left) / rect.width - 0.5) * 2; // -1..1
          const y = ((cy - rect.top) / rect.height - 0.5) * -2; // invert y
          el.style.setProperty('--mx', x);
          el.style.setProperty('--my', y);
        }
        function onLeave(){
          el.style.setProperty('--mx', '0');
          el.style.setProperty('--my', '0');
          rect = null;
        }
        el.addEventListener('mousemove', onMove);
        el.addEventListener('mouseleave', onLeave);
        el.addEventListener('touchmove', onMove, {passive:true});
        el.addEventListener('touchend', onLeave);
      });
    }

  // Pointer-driven root updates and per-header listeners are conditional
  // and will be attached only when data-three-d === 'true'.

    // simple typewriter for hero
    function startHeroTypewriter(){
      const el = document.getElementById('hero-type');
      if (!el) return;
      const phrases = [
        'Full‑stack web developer',
        'Retro UI & UX enthusiast',
        'EGA-inspired designs',
        'Subdomain-powered apps'
      ];
      let pi = 0, ci = 0, deleting = false;
      function tick(){
        const phrase = phrases[pi];
        if (!deleting){
          ci++;
          el.textContent = phrase.slice(0, ci);
          if (ci === phrase.length){
            deleting = true;
            setTimeout(tick, 900);
            return;
          }
        } else {
          ci--;
          el.textContent = phrase.slice(0, ci);
          if (ci === 0){
            deleting = false;
            pi = (pi + 1) % phrases.length;
          }
        }
        setTimeout(tick, deleting ? 60 : 90 + Math.random()*80);
      }
      tick();
    }

    /* Particle system (lightweight) */
    function initParticles(){
      const canvas = document.getElementById('particle-canvas');
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      let w = 0, h = 0, particles = [], raf = null;
      function resize(){ w = canvas.width = window.innerWidth; h = canvas.height = window.innerHeight; }
      function makeParticles(){
        particles = [];
        const count = Math.min(120, Math.floor((w * h) / 60000));
        for(let i=0;i<count;i++){
          particles.push({
            x: Math.random()*w,
            y: Math.random()*h,
            r: 0.6 + Math.random()*1.8,
            vx: (Math.random()-0.5)*0.2,
            vy: (Math.random()-0.5)*0.2,
            alpha: 0.08 + Math.random()*0.22
          });
        }
      }
      function step(){
        if (document.documentElement.dataset.reduceMotion === 'true'){
          ctx.clearRect(0,0,w,h);
          raf = requestAnimationFrame(step);
          return;
        }
        ctx.clearRect(0,0,w,h);
        for(const p of particles){
          p.x += p.vx; p.y += p.vy;
          if (p.x < -10) p.x = w + 10; if (p.x > w + 10) p.x = -10;
          if (p.y < -10) p.y = h + 10; if (p.y > h + 10) p.y = -10;
          ctx.beginPath();
          try{
            var cval = getComputedStyle(document.documentElement).getPropertyValue('--ega-cyan').trim();
            ctx.fillStyle = 'rgba(' + cval + ', ' + p.alpha + ')';
          } catch(e){
            ctx.fillStyle = 'rgba(255,255,255,' + p.alpha + ')';
          }
          ctx.arc(p.x, p.y, p.r, 0, Math.PI*2);
          ctx.fill();
        }
        raf = requestAnimationFrame(step);
      }
      function start(){
        resize(); makeParticles();
        if (raf) cancelAnimationFrame(raf);
        raf = requestAnimationFrame(step);
      }
      window.addEventListener('resize', ()=>{ resize(); makeParticles(); });
      start();
    }

    /* Tilt handlers for .tilt-card elements */
    function attachTiltCards(){
      const cards = document.querySelectorAll('.tilt-card');
      cards.forEach(card => {
        function onMove(e){
          const t = e.touches && e.touches[0] ? e.touches[0] : e;
          const rect = card.getBoundingClientRect();
          const cx = t.clientX - rect.left;
          const cy = t.clientY - rect.top;
          const x = ((cx / rect.width) - 0.5) * 2; // -1..1
          const y = ((cy / rect.height) - 0.5) * -2;
          card.style.setProperty('--tcx', x);
          card.style.setProperty('--tcy', y);
        }
        function onLeave(){ card.style.setProperty('--tcx', '0'); card.style.setProperty('--tcy', '0'); }
        card.addEventListener('pointermove', onMove);
        card.addEventListener('pointerleave', onLeave);
        card.addEventListener('touchmove', onMove, {passive:true});
      });
    }

    /* Reduce-motion toggle: set html[data-reduce-motion] and persist */
    function initReduceMotionToggle(){
      const btn = document.getElementById('motion-toggle');
      if (!btn) return;
      const root = document.documentElement;
      const saved = localStorage.getItem('alsenda-reduce-motion');
      if (saved) root.setAttribute('data-reduce-motion', saved);
      function updateBtn(){ btn.setAttribute('aria-pressed', root.getAttribute('data-reduce-motion') === 'true' ? 'true' : 'false'); }
      btn.addEventListener('click', ()=>{
        const next = root.getAttribute('data-reduce-motion') === 'true' ? 'false' : 'true';
        root.setAttribute('data-reduce-motion', next);
        localStorage.setItem('alsenda-reduce-motion', next);
        updateBtn();
      });
      updateBtn();
    }

    // Attach listeners after DOM is ready
    function onReady(){
      try{
        const threeD = document.documentElement.getAttribute('data-three-d') === 'true';
        if (threeD){
          window.addEventListener('mousemove', updateRootFromEvent);
          window.addEventListener('touchmove', updateRootFromEvent, {passive:true});
          attachHeaderListeners();
        }
      }catch(e){}
      // always start these regardless of 3D flag
      startHeroTypewriter();
      initParticles();
      attachTiltCards();
      initReduceMotionToggle();
    }
    if (document.readyState === 'complete' || document.readyState === 'interactive'){
      onReady();
    } else {
      document.addEventListener('DOMContentLoaded', onReady);
    }
  } catch (err) { console.error(err); }
})();`
          }}
        />
        <ThemeProvider>
          <div className="max-w-[1200px] mx-auto px-4 sm:px-6">
            <button id="motion-toggle" className="motion-toggle" aria-pressed="false" title="Reduce motion">Reduce motion</button>
            <CRTPageTransition>
              {children}
            </CRTPageTransition>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
